batch_size: 3 
num_samples: 10
num_epochs: 10000


optim:
  optimizer: adam 
  weight_decay: 0
  momentum: 0.3

  lr:
    scheduler: cos
    anneal_step: 100
    anneal_factor: 0.9
    warmup_steps: 50
    cos_T: 5000
    cos_min: 1e-8

  lr_i: 0.00003
  lr_o: 0.00003
    

mu:
  init: 2000.0
  step: 1
  step_size: 0.001
  max: 50000.0
  min: 0.0
  value: 1.0
  warmup: 100

entr_coef: 10.0
loss_config: "normalize"
